### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GWan1234** [vinz486/Fingerprints-reader-R503---R502-esp8266-mqtt-Home-Assistant#8]
{
	"resource": "/c:/Users/Wanzi/Documents/GitHub/fingerprint-r503-mqtt/fingerprint-mqtt/.pio/libdeps/d1_mini_lite/PubSubClient/src/PubSubClient.cpp",
	"owner": "cpp",
	"severity": 4,
	"message": "comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]",
	"startLineNumber": 523,
	"startColumn": 16,
	"endLineNumber": 523,
	"endColumn": 16
}
Great project!
By the way, is the version of led status indication planned?

**Comment by vinz486** [comment]
Hi,
sorry but I have no spare time to spend on this project.
