### ISSUE TITLE
Wemos D1 mini/PRO - Not detecting R503 v1.2 sensor

### ISSUE THREAD

**Issue by bad-gargoyle** [vinz486/Fingerprints-reader-R503---R502-esp8266-mqtt-Home-Assistant#9]
Will this project run o D1 mini PRO?

Upload was succesfull, but I have some kind of boot loop (led blinks with 3-4s delays) and Wifi hotspot doesn't appear.

**Comment by bad-gargoyle** [comment]
I have R503 v1.2 (with cables: red, black, yellow, brown, blue, white). I've contacted GROW and they said that is basicly the same sensor as with cables yellow and green (I guass it differs with waterproff ability only).

I tested this sensor with USB to TTL converter and GROW "TestDemo_V3.012" program and it works all fine but when I run monitor (pio device monitor) I have:
"Looking for sensor...KO.
Sensor not found: check serial connection on green/yellow cables."

Any clue what is wrong? Please help...

PS I even ordered and run same tests on Wemos mini NOT-PRO to be 100% sure that is not the board problem. ;-)

**Comment by bad-gargoyle** [comment]
Ok, I've managed to solve this by myself. ;-) The problem Was that project suggested to use D4 and D5 GPIO ports. Those ports on WEMOS are partly used for serial port interface communication (D5 is for SPI SCK, D6 is for SPI MISO). When I've changed (phisicly and in skech) ports to D3 and D4 everything started to work.

**Comment by vinz486** [comment]
Thank you for your suggestion: strange that my wemos is working perfectly.
